DeepSeek:
  model_name: unsloth/DeepSeek-R1-Distill-Llama-8B-unsloth-bnb-4bit
  quantization_config: 
    load_in_4bit: true
    llm_int8_enable_fp32_cpu_offload: true
  device_map: auto



SFT_deepseek:
  pretrained_model_name_or_path: "./outputs/checkpoints/finetuned_model"
  quantization_config:
    load_in_4bit: true
    llm_int8_enable_fp32_cpu_offload: true
  device_map: "auto"