trianing:
  output_dir: ./results
  evaluation_strategy: epoch
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  max_steps: 5
  learning_rate: 2e-4
  optim: adamw_8bit
  weight_decay: 0.01
  save_strategy: steps   # save periodically
  save_steps: 5             # every 5 steps
  report_to: none        # disable W&B
